apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadlofe5874-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadlofe5874-tenant-component
    app.kubernetes.io/part-of: loadlofe5874-tenant-app
  name: loadlofe5874-tenant-component
  namespace: loadlofe5874-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadlofe5874-tenant-component
    weight: null
status: {}
